blank_issues_enabled: true
contact_links:
  - name: Security policy
    url: https://github.com/thomascarter613/monorepo-starter/security/policy
    about: Please review the security policy before reporting vulnerabilities.
