#!/usr/bin/env bash
set -euo pipefail

labels=(
  "type: feature|0E8A16|New product, repo, CLI, automation, app, service, package, or workflow capability"
  "type: bug|D73A4A|Something broken, incorrect, inconsistent, or not working as expected"
  "type: docs|0075CA|Documentation work"
  "type: task|C2E0C6|Concrete implementation, maintenance, governance, or tooling task"
  "type: adr|5319E7|Architecture decision work"
  "type: refactor|FBCA04|Code or structure improvement without behavior change"
  "type: test|1D76DB|Testing work"
  "type: build|BFDADC|Build tooling or packaging work"
  "type: ci|2F4F4F|Continuous integration or automation work"
  "type: security|B60205|Security-sensitive work"
  "type: governance|7057FF|Governance, policy, or repository rules"
  "type: release|0052CC|Release, changelog, versioning, or provenance work"
  "status: needs triage|EDEDED|Needs initial review and classification"
  "status: needs decision|D4C5F9|Needs an explicit decision before implementation"
  "status: ready|0E8A16|Ready for implementation"
  "status: blocked|D73A4A|Blocked by another decision, task, or dependency"
  "status: in progress|FBCA04|Currently being worked on"
  "status: needs review|1D76DB|Ready for review"
  "status: done|C5DEF5|Completed"
  "priority: critical|B60205|Critical priority"
  "priority: high|D93F0B|High priority"
  "priority: medium|FBCA04|Medium priority"
  "priority: low|0E8A16|Low priority"
  "area: repo|5319E7|Repository foundation"
  "area: docs|0075CA|Documentation"
  "area: architecture|5319E7|Architecture and design"
  "area: governance|7057FF|Governance and policy"
  "area: tooling|BFDADC|Developer tooling"
  "area: ci|2F4F4F|CI and automation"
  "area: security|B60205|Security"
  "area: supply-chain|B60205|Supply chain and provenance"
  "area: cli|1D76DB|moro CLI"
  "area: templates|C2E0C6|Templates"
  "area: profiles|C2E0C6|Profiles"
  "area: apps|0E8A16|Applications"
  "area: services|D4C5F9|Services and workers"
  "area: packages|1D76DB|Shared packages"
  "area: infra|2F4F4F|Infrastructure"
  "area: testing|1D76DB|Testing"
  "area: release|0052CC|Release management"
  "effort: small|C5DEF5|Small effort"
  "effort: medium|FBCA04|Medium effort"
  "effort: large|D93F0B|Large effort"
  "effort: epic|5319E7|Epic-sized effort"
  "risk: low|0E8A16|Low implementation risk"
  "risk: medium|FBCA04|Medium implementation risk"
  "risk: high|D73A4A|High implementation risk"
  "risk: breaking-change|B60205|Breaking change risk"
  "automation: candidate|C2E0C6|Good candidate for automation"
  "automation: generated|BFDADC|Generated or automation-managed"
  "automation: needs-sync|FBCA04|Needs synchronization with external state"
  "automation: do-not-automate|D73A4A|Should not be automated casually"
)

for item in "${labels[@]}"; do
  IFS='|' read -r name color description <<< "$item"
  if gh label list --limit 500 --json name -q '.[].name' | grep -Fxq "$name"; then
    gh label edit "$name" --color "$color" --description "$description"
  else
    gh label create "$name" --color "$color" --description "$description"
  fi
done
